personality = "pragmatic"

[tui]
status_line = ["model-with-reasoning", "project-name", "git-branch", "five-hour-limit", "weekly-limit"]

[features]
memories = true

[memories]
generate_memories = true
use_memories = true

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true
